- hosts: localhost
  become: yes
  become_method: sudo
  become_user: root
  vars:
    #ansible_python_interpreter: /usr/bin/python3
    docker_tag: "v4.0"  # Change this to any tag you want
    container_name: "abctechnologies_ansible"
    image_name: "mahshamim/abstechnologies_ansible"
    docker_username: "mahshamim"
    docker_password: "01614747054@R!f"
    kubeconfig_path: ~/.kube/config
    deployment_file: /home/ubuntu/industry-grade-project-i/k8s_deployments/deployment.yml
    service_file: /home/ubuntu/industry-grade-project-i/k8s_deployments/service.yaml
  tasks:
    #- name: Check Python environment
      #command: python3 -c "import kubernetes"

    - name: Check if Docker is already installed
      command: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: docker_installed.rc != 0

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: true

    - name: Build WAR file using Maven (if applicable)
      command: mvn clean package
      args:
        chdir: ./
      when: docker_installed.rc == 0  # Run only if Docker is installed

    - name: Build Docker Image
      command: docker build -t {{ image_name }} .

    - name: Stop existing Docker container if running
      docker_container:
          name: "{{ container_name }}"
          state: absent
      ignore_errors: true

    - name: Remove existing Docker container if exists
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: true

    - name: Run Docker Container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        published_ports:
          - "9292:8080"

    - name: Log in to Docker Hub
      command: docker login -u "{{ docker_username }}" -p "{{ docker_password }}"
      no_log: true

    - name: Tag Docker image for Docker Hub
      command: docker tag {{ image_name }} "{{ image_name }}:{{ docker_tag }}"

    - name: Push Docker image to Docker Hub
      command: docker push "{{ image_name }}:{{ docker_tag }}"

    - name: Apply Kubernetes Deployment
      ansible.builtin.k8s:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        definition: "{{ lookup('file', deployment_file) }}"

    - name: Apply Kubernetes Service
      ansible.builtin.k8s:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        definition: "{{ lookup('file', service_file) }}"